version: '3.8'

services:
  bookstoreapp:
    image: bookstore:1
    environment:
      # Activa el perfil de desarrollo
      - SPRING_PROFILES_ACTIVE=dev
      # Configuración de PostgreSQL
      - spring.datasource.url=jdbc:postgresql://bookstore_db:5432/book
      - spring.datasource.username=postgres
      - spring.datasource.password=12345
      - spring.datasource.driver-class-name=org.postgresql.Driver
      # Dialecto de Hibernate para PostgreSQL
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - bookstore_net
      - traefik-public
    ports:
      - "8080:8080"  # Exponer el puerto correctamente
    deploy:
      replicas: 2  # Ejecuta 2 instancias de bookstoreapp
      labels:
        - "traefik.enable=true"  # Rutas principales para la aplicación
        - "traefik.http.routers.bookstoreapp.entrypoints=http"
        - "traefik.http.routers.bookstoreapp.rule=Host(`bookstoreapp.byrorm.com`)"
        - "traefik.http.middlewares.bookstoreapp-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.bookstoreapp.middlewares=bookstoreapp-https-redirect"
        # Ruta segura HTTPS
        - "traefik.http.routers.bookstoreapp-secure.entrypoints=https"
        - "traefik.http.routers.bookstoreapp-secure.rule=Host(`bookstore.byrorm.com`)"
        - "traefik.http.routers.bookstoreapp-secure.tls=true"
        - "traefik.http.routers.bookstoreapp-secure.tls.certresolver=http"
        - "traefik.http.routers.bookstoreapp-secure.service=bookstoreapp"
        - "traefik.http.services.bookstoreapp.loadbalancer.server.port=8080"
        - "traefik.docker.network=traefik-public"
        # Subdominio adicional
        - "traefik.http.routers.bookstoreapp_api.entrypoints=http"
        - "traefik.http.routers.bookstoreapp_api.rule=Host(`api.byrorm.com`)"
        - "traefik.http.routers.bookstoreapp_api.middlewares=bookstoreapp-https-redirect"
        - "traefik.http.routers.bookstoreapp_api-secure.entrypoints=https"
        - "traefik.http.routers.bookstoreapp_api-secure.rule=Host(`api.byrorm.com`)"
        - "traefik.http.routers.bookstoreapp_api-secure.tls=true"
        - "traefik.http.routers.bookstoreapp_api-secure.tls.certresolver=http"
        - "traefik.http.routers.bookstoreapp_api-secure.service=bookstoreapp"
    depends_on:
      - bookstore_db

  bookstore_db:
    image: postgres:14
    environment:
      - TZ=America/Guayaquil
      - POSTGRES_DB=book
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    networks:
      - bookstore_net

volumes:
  db_data:
    external: true

networks:
  bookstore_net:
    external: true
  traefik-public:
    external: true
